const dsaSongRows = [
  ["Neon Sunrise", "Luna Drift", "City Lights", 214, "Energetic", 1],
  ["Binary Heart", "Algo Beats", "Code & Chill", 187, "Focus", 2],
  ["Moonlit Queue", "Mira Sol", "Night Drive", 241, "Dreamy", 3],
  ["Stack Overflow", "The Debuggers", "Runtime", 199, "Rock", 4],
  ["Velvet Cache", "Nova Lane", "Soft Signals", 226, "Chill", 5],
  ["Hashmap Halo", "Ari Pulse", "Index Theory", 203, "Focus", 6],
  ["Sorted Skies", "Cloud Array", "Ascending", 252, "Ambient", 7],
  ["Midnight Vector", "Signal Bloom", "After Hours", 181, "Pop", 8],
  ["Recursive Rain", "Echo Frames", "Loop Dreams", 235, "Dreamy", 9],
  ["Graph Groove", "Node Theory", "Connected", 207, "Dance", 10],
  ["Searchlight", "Riya Ray", "Found You", 192, "Pop", 11],
  ["Dynamic Waves", "Kai Mono", "Resizable", 268, "Electronic", 12],
  ["Pointer Parade", "Linked Souls", "References", 221, "Indie", 13],
  ["Heap Heat", "DJ Priority", "Top Level", 176, "Dance", 14],
  ["Merge Moment", "Tara Flux", "Divide", 244, "Ambient", 15],
  ["Quick Pulse", "Pivot Club", "Partition", 189, "Electronic", 16],
  ["Linear Love", "Sam Sequence", "Straight Path", 232, "Chill", 1],
  ["Node by Node", "List Lovers", "Linked", 205, "Indie", 2],
  ["Index 404", "Null Point", "Not Found", 197, "Rock", 3],
  ["Golden Ratio", "Phi Sound", "Patterns", 255, "Classical", 4],
  ["Greedy Stars", "Optima", "Local Best", 212, "Pop", 5],
  ["Backtrack", "Maze Runnerz", "Try Again", 229, "Electronic", 6],
  ["Base Case", "Recursa", "Return", 184, "Focus", 7],
  ["Edge Weight", "Dijkstra Drive", "Shortest", 238, "Dance", 8],
  ["Beatify Anthem", "Beatify Studio", "Lab Demo", 201, "Brand", 9]
];

export const arijitSongRows = [
  ["Tum Hi Ho", "Arijit Singh", "Aashiqui 2", 262, "Romantic", 1],
  ["Channa Mereya", "Arijit Singh", "Ae Dil Hai Mushkil", 289, "Emotional", 2],
  ["Ae Dil Hai Mushkil", "Arijit Singh", "Ae Dil Hai Mushkil", 269, "Emotional", 3],
  ["Kesariya", "Arijit Singh", "Brahmastra", 268, "Romantic", 4],
  ["Shayad", "Arijit Singh", "Love Aaj Kal", 247, "Romantic", 5],
  ["Agar Tum Saath Ho", "Arijit Singh", "Tamasha", 341, "Emotional", 6],
  ["Gerua", "Arijit Singh", "Dilwale", 346, "Romantic", 7],
  ["Raabta", "Arijit Singh", "Agent Vinod", 243, "Romantic", 8],
  ["Kabira Encore", "Arijit Singh", "Yeh Jawaani Hai Deewani", 270, "Soulful", 9],
  ["Muskurane", "Arijit Singh", "CityLights", 334, "Romantic", 10],
  ["Phir Bhi Tumko Chaahunga", "Arijit Singh", "Half Girlfriend", 351, "Romantic", 11],
  ["Hawayein", "Arijit Singh", "Jab Harry Met Sejal", 289, "Travel", 12],
  ["Zaalima", "Arijit Singh", "Raees", 299, "Romantic", 13],
  ["Tera Yaar Hoon Main", "Arijit Singh", "Sonu Ke Titu Ki Sweety", 264, "Friendship", 14],
  ["Enna Sona", "Arijit Singh", "OK Jaanu", 213, "Romantic", 15],
  ["Soch Na Sake", "Arijit Singh", "Airlift", 281, "Romantic", 16],
  ["Bolna", "Arijit Singh", "Kapoor & Sons", 212, "Romantic", 1],
  ["Nashe Si Chadh Gayi", "Arijit Singh", "Befikre", 238, "Dance", 2],
  ["Khairiyat", "Arijit Singh", "Chhichhore", 280, "Emotional", 3],
  ["Kalank Title Track", "Arijit Singh", "Kalank", 311, "Soulful", 4],
  ["Ve Maahi", "Arijit Singh", "Kesari", 223, "Romantic", 5],
  ["Pal", "Arijit Singh", "Jalebi", 247, "Romantic", 6],
  ["Hamari Adhuri Kahani", "Arijit Singh", "Hamari Adhuri Kahani", 398, "Emotional", 7],
  ["Janam Janam", "Arijit Singh", "Dilwale", 237, "Romantic", 8],
  ["Laal Ishq", "Arijit Singh", "Goliyon Ki Raasleela Ram-Leela", 389, "Classical", 9],
  ["Duaa", "Arijit Singh", "Shanghai", 260, "Soulful", 10],
  ["Ilahi", "Arijit Singh", "Yeh Jawaani Hai Deewani", 229, "Travel", 11],
  ["Samjhawan", "Arijit Singh", "Humpty Sharma Ki Dulhania", 269, "Romantic", 12],
  ["Sanam Re", "Arijit Singh", "Sanam Re", 308, "Romantic", 13],
  ["Lambiyaan Si Judaiyaan", "Arijit Singh", "Raabta", 238, "Emotional", 14],
  ["Bulleya", "Arijit Singh", "Ae Dil Hai Mushkil", 348, "Rock", 15],
  ["Bekhayali", "Arijit Singh", "Kabir Singh", 371, "Emotional", 16],
  ["Roke Na Ruke Naina", "Arijit Singh", "Badrinath Ki Dulhania", 278, "Emotional", 1],
  ["Naina", "Arijit Singh", "Dangal", 225, "Soulful", 2],
  ["Saware", "Arijit Singh", "Phantom", 321, "Romantic", 3],
  ["Judai", "Arijit Singh", "Badlapur", 272, "Emotional", 4],
  ["Darkhaast", "Arijit Singh", "Shivaay", 374, "Romantic", 5],
  ["Galti Se Mistake", "Arijit Singh", "Jagga Jasoos", 203, "Fun", 6],
  ["First Class", "Arijit Singh", "Kalank", 275, "Dance", 7],
  ["Ghungroo", "Arijit Singh", "War", 302, "Dance", 8],
  ["Tujhe Kitna Chahne Lage", "Arijit Singh", "Kabir Singh", 284, "Romantic", 9],
  ["Apna Bana Le", "Arijit Singh", "Bhediya", 261, "Romantic", 10],
  ["Heeriye", "Arijit Singh", "Heeriye", 194, "Pop", 11],
  ["O Maahi", "Arijit Singh", "Dunki", 234, "Romantic", 12],
  ["Satranga", "Arijit Singh", "Animal", 271, "Soulful", 13]
];

export const sampleSongs = [...dsaSongRows, ...arijitSongRows].map(([title, artist, album, duration, mood, n], index) => ({
  title,
  artist,
  album,
  duration,
  mood,
  plays: Math.max(250, 2200 - index * 23),
  coverImage: `https://images.unsplash.com/photo-${[
    "1493225457124-a3eb161ffa5f",
    "1511379938547-c1f69419868d",
    "1500530855697-b586d89ba3ee",
    "1508700115892-45ecd05ae2ad",
    "1516280440614-37939bbacd81",
    "1511671782779-c97d3d27a1d4",
    "1483412033650-1015ddeb83d1",
    "1459749411175-04bf5292ceea",
    "1499364615650-ec38552f4f34"
  ][(n - 1) % 9]}?auto=format&fit=crop&w=500&q=80`,
  audioUrl: `https://www.soundhelix.com/examples/mp3/SoundHelix-Song-${n}.mp3`,
  youtubeQuery: artist === "Arijit Singh"
    ? `${title} ${artist} ${album} official song`
    : `${title} ${artist} music`
}));
